#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 30 13:32:59 2018

@author: dade
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url_wo_year='http://rankings.ft.com/businessschoolrankings/masters-in-management-'
output_dict = {}


years = ['2014']
for year in years:
    url = url_wo_year + year
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    rankings_table = soup.find(id = "rankingstable")
    rankings_table.prettify()
    output = pd.read_html(url)
    k = 0
    for i in output[0].columns:
        if "Unnamed" in i:
            output[0].drop("Unnamed: " + str(k),axis =1, inplace = True)
            k += 1
    output = output[0][:-1]
    
    #MISSING PART FOR SCALE ADJUSTMENTS!!!!!!
    
    output_dict[year] = output
# print(output_dict)
df = output_dict["2014"]
column_names = df.columns
column_names
     
    
years = ['2015','2016']
for year in years:
    url = url_wo_year + year
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    rankings_table = soup.find(id = "rankingstable")
    rankings_table.prettify()
    output = pd.read_html(url)
    k = 0
    for i in output[0].columns:
        if "Unnamed" in i:
            output[0].drop("Unnamed: " + str(k),axis =1, inplace = True)
            k += 1
    output = output[0][:-1]
    
    output["Salary today (US$)[1]"] = output["Salary today (US$)[1]"] / 10000
    output['Weighted sal. ($)[2]'] = output["Weighted sal. ($)[2]"] / 10000
    output["Value[3]"] = output["Value[3]"] / 10
    output["Careers[4]"] = output["Careers[4]"] / 100
    output["Aims achieved[5]"] = output["Aims achieved[5]"] / 10
    output["Placements[6]"] = output["Placements[6]"] / 10
    output["Wom. faculty[8]"] = output["Wom. faculty[8]"] / 10
    output["Wom. students[9]"] = output["Wom. students[9]"] / 10
    output["Wom. board[10]"] = output["Wom. board[10]"] / 10
    output["Intl. faculty[11]"] = output["Intl. faculty[11]"] / 10
    output["Intl. students[12]"] = output["Intl. students[12]"] / 10
    output["Intl. board[13]"] = output["Intl. board[13]"] / 10
    output["Intl. mobility[14]"] = output["Intl. mobility[14]"] / 10
    output["Intl. course[15]"] = output["Intl. course[15]"] / 10
    output["Languages[16]"] = output["Languages[16]"] / 10
    output["PhD Faculty[17]"] = output["PhD Faculty[17]"] / 10
    output["Prog. length[18]"] = output["Prog. length[18]"] / 10
    output["Internships[19]"] = output["Internships[19]"] / 10
    
    output_dict[year] = output
    
OUT= output_dict["2015"]
column_names = OUT.columns
column_names
print(OUT)
print(OUT['Internships[15]'])  





years = ['2017','2018']
for year in years:
    url = url_wo_year + year
    page = requests.get(url)
    soup = BeautifulSoup(page.content, 'html.parser')
    rankings_table = soup.find(id = "rankingstable")
    rankings_table.prettify()
    output = pd.read_html(url)
    k = 0
    for i in output[0].columns:
        if "Unnamed" in i:
            output[0].drop("Unnamed: " + str(k),axis =1, inplace = True)
            k += 1
    
    output = output[0][:-1]

    output["Salary today (US$)[1]"] = output["Salary today (US$)[1]"] / 10000
    output['Weighted salary (US$)[2]'] = output["Weighted salary (US$)[2]"] / 10000
    output["Salary percentage increase"] = output["Salary percentage increase"] / 100
    output["Value[3]"] = output["Value[3]"] / 10
    output["Career progress rank"] = output["Career progress rank"] / 100
    output["Aims achieved[4]"] = output["Aims achieved[4]"] / 10
    output["Careers service rank"] = output["Careers service rank"] / 10
    output["Female faculty (%)"] = output["Female faculty (%)"] / 10
    output["Female students (%)"] = output["Female students (%)"] / 100
    output["Wom. board[6]"] = output["Wom. board[6]"] / 10
    output['Intl. faculty[7]'] = output["Intl. faculty[7]"] / 10
    output["Intl. students[8]"] = output["Intl. students[8]"] / 10
    output["Intl. board[9]"] = output["Intl. board[9]"] / 10
    output["Intl. mobility[10]"] = output["Intl. mobility[10]"] / 10
    output["Intl. course[11]"] = output["Intl. course[11]"] / 10
    output["Languages[12]"] = output["Languages[12]"] / 10
    output["PhD Faculty[13]"] = output["PhD Faculty[13]"] / 10
    output["Prog. length[14]"] = output["Prog. length[14]"] / 10
    output["Internships[15]"] = output["Internships[15]"] / 10
    
    output_dict[year] = output
    
OUTPUT= output_dict["2018"]
column_names = OUTPUT.columns
column_names
print(OUTPUT)
print(OUTPUT['Internships[15]'])    
    
